openapi: 3.0.0
info:
  title: Ejercicios
  description: >-
    **This is the documentation for the exercises.**

    
    **Here you can try the three exercises and see all the posible responses.**
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/normalize:
    get:
      tags:
        - Ejercicios
      summary: StreetNormalizer
      description: >-
        **Return a normalized direction based in the parameters you
        input.**


        **Obligatory parameters:**


        - "**calle**": String

        - "**provincia**": String

        - "**altura**": String
            

         **Optional parameters**:


        - "**departamento**": String
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '71'
            ETag:
              schema:
                type: string
                example: W/"47-dYknz9qeWrzHiH7Vu6AC2nDL+wo"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 03:11:52 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 200 with department
                  value:
                    msg: >-
                      AV CORRIENTES 400, Comuna 1, Ciudad Autónoma de Buenos
                      Aires
                example-1:
                  summary: 200 without department
                  value:
                    msg:
                      - >-
                        Localidad con esa calle: Ciudad Autónoma de Buenos
                        Aires. Departamento de esa localidad: Comuna 1
                      - >-
                        Localidad con esa calle: Necochea - Quequén.
                        Departamento de esa localidad: Necochea
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '44'
            ETag:
              schema:
                type: string
                example: W/"2c-eIwdIIQKVao2YyoY+Joi8rKOd8w"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 03:09:17 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 400 wrong entry of parameters
                  value:
                    Error: Parameters not entered correctly
                example-1:
                  summary: 400 street not found
                  value:
                    Error: Street not found
  /api/distanceCalculator/:
    get:
      tags:
        - Ejercicios
      summary: distanceCalculator
      description: >-
        **Calculate the distance ,between the normalized direction entered
        and the Obelisc of Buenos Aires, and return if it's in less or more than
        5 kilometers.**


        **Obligatory parameters:**


        - "**direccion**":String
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '53'
            ETag:
              schema:
                type: string
                example: W/"35-dj5ma+zJRJF47htK/k+I/vTk5VM"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 03:05:48 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 200 less than 5km
                  value:
                    msg: Estas a menos de 5 Kilómetros del Obelisco
                example-1:
                  summary: 200 more than 5km
                  value:
                    msg: Estas lejos del Obelisco
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '37'
            ETag:
              schema:
                type: string
                example: W/"25-VQbLab+uUBGozjBIApjJpYy7mik"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 03:16:40 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 400 street not found
                  value:
                    Error: No conozco esa dirección
                example-1:
                  summary: 400 direccion needed
                  value:
                    Error: Parameter direccion needed
  /api/currencyFinder/:
    get:
      tags:
        - Ejercicios
      summary: CurrencyFinder
      description: |-
        **Find the currency of the country entered.**

        **Obligatory parameters:**

        - "**pais**": String
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '44'
            ETag:
              schema:
                type: string
                example: W/"2c-QTDzh148IiN7QRcUaKDfVOpI2iA"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 04:10:31 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                msg: La moneda de Brazil es Brazil Real
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '31'
            ETag:
              schema:
                type: string
                example: W/"1f-PByszvMa6izCc2FbkrIwtXd3Fe0"
            Date:
              schema:
                type: string
                example: Wed, 26 Apr 2023 04:13:42 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: 400 country not found
                  value:
                    Error: País no encontrado
                example-1:
                  summary: 400 pais needed
                  value:
                    Error: Parameter pais needed